[package]
name = "inrush"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { version = "0.88.1", features = ["runtime", "derive", "ws", "unstable-runtime"] }
k8s-openapi = { version = "0.21.1", features = ["latest"] }
futures = "0.3.30"
serde_json = "1.0.117"
tokio = { version = "1.36.0", features=["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
thiserror = "1.0.61"
anyhow = "1.0.80"
serde = { version = "1.0.202", features = ["derive"] }
tokio-util = "0.7.10"
askama = "0.12.1"
schemars = "*"
serde_yaml = "0.9.32"
resolv-conf = "0.7.0"
